ignore:
  # https://ubuntu.com/security/CVE-2022-3649
  # New priority: medium
  - vulnerability: CVE-2022-3649
  # https://ubuntu.com/security/CVE-2019-19814
  # New priority: low
  - vulnerability: CVE-2019-19814