name: "Test Workstations"

on:
  push:
    paths:
      - 'workstations/Dockerfile'
  pull_request:
    paths:
      - 'workstations/Dockerfile'
  workflow_dispatch:

jobs:

  test:
    name: Build workstations image
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
      - name: Build 🧪
        run: |
          podman build . \
            --file "workstations/Dockerfile" \
            --network "slirp4netns" \
            --platform "linux/amd64" \
            --tag "cloud-tools-container:local"
